export const THEMES = {
  default: {
    id: 'default',
    name: 'Victorian Library',
    background: '#1a1208',
    surface: '#221608',
    inputBg: '#1c1408',
    accent: '#c9913d',
    secondaryAccent: '#8a6930',
    textColor: '#ede0cc',
    textMuted: '#6e5542',
    borderColor: '#2e200a',
    bgGlow: 'rgba(201,145,61,0.06)',
    glowX: '50%', glowY: '40%',
    symbols: ['dust', 'book', 'feather', 'dust', 'feather'],
    backgroundElements: [],
    fontMood: 'warm',
    atmosphereText: 'A candlelit library awaits your search…',
    particleConfig: { count: 12, speedRange: [22000, 42000], sizeRange: [10, 22] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'dark-romantasy': {
    id: 'dark-romantasy',
    name: 'Dark Romantasy',
    background: '#0c0808',
    surface: '#160a0a',
    inputBg: '#110808',
    accent: '#8b1a1a',
    secondaryAccent: '#b0b0c8',
    textColor: '#f0e0e0',
    textMuted: '#7a5050',
    borderColor: '#280e0e',
    bgGlow: 'rgba(139,26,26,0.12)',
    glowX: '50%', glowY: '35%',
    symbols: ['rose-petal', 'dagger', 'crescent-moon', 'star', 'rose-petal'],
    backgroundElements: ['cathedral'],
    fontMood: 'heavy',
    atmosphereText: 'Blood moon rising over gothic spires…',
    particleConfig: { count: 10, speedRange: [25000, 48000], sizeRange: [12, 26] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'fantasy-light': {
    id: 'fantasy-light',
    name: 'Fantasy',
    background: '#0e1f0e',
    surface: '#122414',
    inputBg: '#0c1c0c',
    accent: '#b8984a',
    secondaryAccent: '#c8a0a0',
    textColor: '#e0f0d8',
    textMuted: '#607850',
    borderColor: '#1c3018',
    bgGlow: 'rgba(120,180,80,0.07)',
    glowX: '50%', glowY: '45%',
    symbols: ['sparkle', 'feather', 'rose-petal', 'sparkle', 'feather'],
    backgroundElements: ['castle'],
    fontMood: 'warm',
    atmosphereText: 'Soft ember light drifts through the enchanted glade…',
    particleConfig: { count: 14, speedRange: [18000, 36000], sizeRange: [8, 20] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'fantasy-dark': {
    id: 'fantasy-dark',
    name: 'Dark Fantasy',
    background: '#10101e',
    surface: '#14142a',
    inputBg: '#0c0c1a',
    accent: '#7060b0',
    secondaryAccent: '#405840',
    textColor: '#d8d8f0',
    textMuted: '#505080',
    borderColor: '#20203a',
    bgGlow: 'rgba(80,60,180,0.10)',
    glowX: '50%', glowY: '40%',
    symbols: ['dragon', 'sword', 'storm-cloud', 'star'],
    backgroundElements: ['mountains'],
    fontMood: 'bold',
    atmosphereText: 'Storm clouds gather above ancient peaks…',
    particleConfig: { count: 8, speedRange: [22000, 44000], sizeRange: [14, 28] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'historical-fiction': {
    id: 'historical-fiction',
    name: 'Historical',
    background: '#221808',
    surface: '#2c2010',
    inputBg: '#1e1608',
    accent: '#c0964a',
    secondaryAccent: '#806840',
    textColor: '#ede0b8',
    textMuted: '#807050',
    borderColor: '#382c12',
    bgGlow: 'rgba(192,150,74,0.07)',
    glowX: '50%', glowY: '40%',
    symbols: ['quill', 'ink-drop', 'wax-seal', 'feather'],
    backgroundElements: [],
    fontMood: 'classic',
    atmosphereText: 'The scent of aged parchment and candlewax…',
    particleConfig: { count: 8, speedRange: [32000, 58000], sizeRange: [10, 20] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'scifi-cosmic': {
    id: 'scifi-cosmic',
    name: 'Cosmic',
    background: '#04041a',
    surface: '#08082a',
    inputBg: '#040418',
    accent: '#6050d0',
    secondaryAccent: '#c050c0',
    textColor: '#d8d8ff',
    textMuted: '#404088',
    borderColor: '#101038',
    bgGlow: 'rgba(80,60,220,0.14)',
    glowX: '50%', glowY: '38%',
    symbols: ['star', 'sparkle', 'planet', 'star', 'sparkle'],
    backgroundElements: ['galaxy'],
    fontMood: 'light',
    atmosphereText: 'Somewhere between the stars, a story unfolds…',
    particleConfig: { count: 16, speedRange: [15000, 34000], sizeRange: [6, 18] },
    filmGrain: false,
    transitionDuration: 800,
  },
  'scifi-retro': {
    id: 'scifi-retro',
    name: 'Retro Sci-Fi',
    background: '#120f08',
    surface: '#1c1810',
    inputBg: '#100d08',
    accent: '#c4501a',
    secondaryAccent: '#808890',
    textColor: '#e0d8c8',
    textMuted: '#706050',
    borderColor: '#241e14',
    bgGlow: 'rgba(196,80,26,0.10)',
    glowX: '50%', glowY: '40%',
    symbols: ['star', 'planet', 'spacecraft', 'star'],
    backgroundElements: ['grid'],
    fontMood: 'mono',
    atmosphereText: 'Transmission received from sector seven…',
    particleConfig: { count: 10, speedRange: [20000, 38000], sizeRange: [10, 22] },
    filmGrain: false,
    transitionDuration: 800,
  },
  thriller: {
    id: 'thriller',
    name: 'Thriller',
    background: '#0a0a0a',
    surface: '#111111',
    inputBg: '#070707',
    accent: '#cc1515',
    secondaryAccent: '#555555',
    textColor: '#d0d0d0',
    textMuted: '#484848',
    borderColor: '#1a1a1a',
    bgGlow: 'rgba(200,20,20,0.05)',
    glowX: '80%', glowY: '20%',
    symbols: ['magnifying-glass', 'eye', 'shadowy-figure'],
    backgroundElements: [],
    fontMood: 'typewriter',
    atmosphereText: 'Every shadow conceals a secret…',
    particleConfig: { count: 5, speedRange: [38000, 65000], sizeRange: [10, 18] },
    filmGrain: true,
    transitionDuration: 800,
  },
  horror: {
    id: 'horror',
    name: 'Horror',
    background: '#030303',
    surface: '#060606',
    inputBg: '#020202',
    accent: '#2a6a2a',
    secondaryAccent: '#1a2e1a',
    textColor: '#b8c8b8',
    textMuted: '#304030',
    borderColor: '#0c140c',
    bgGlow: 'rgba(30,100,30,0.06)',
    glowX: '50%', glowY: '60%',
    symbols: ['bare-tree', 'shadowy-figure', 'eye'],
    backgroundElements: [],
    fontMood: 'distressed',
    atmosphereText: 'Something stirs in the dark beyond the page…',
    particleConfig: { count: 5, speedRange: [42000, 72000], sizeRange: [12, 22] },
    filmGrain: true,
    transitionDuration: 1000,
  },
  romance: {
    id: 'romance',
    name: 'Romance',
    background: '#14100a',
    surface: '#1c1610',
    inputBg: '#100e08',
    accent: '#c87060',
    secondaryAccent: '#a0806a',
    textColor: '#f0e4d0',
    textMuted: '#806858',
    borderColor: '#261e14',
    bgGlow: 'rgba(200,112,96,0.08)',
    glowX: '50%', glowY: '38%',
    symbols: ['rose-petal', 'sparkle', 'feather', 'rose-petal'],
    backgroundElements: [],
    fontMood: 'elegant',
    atmosphereText: 'Wildflowers stir in the golden afternoon light…',
    particleConfig: { count: 14, speedRange: [18000, 36000], sizeRange: [8, 20] },
    filmGrain: false,
    transitionDuration: 800,
  },
}

export const DEFAULT_THEME = THEMES.default

export const MOOD_LIST = [
  { id: 'dark-romantasy',    label: 'Dark Romantasy',   color: '#8b1a1a' },
  { id: 'fantasy-light',     label: 'Fantasy',           color: '#4a8a3a' },
  { id: 'fantasy-dark',      label: 'Dark Fantasy',      color: '#5050a0' },
  { id: 'historical-fiction',label: 'Historical',        color: '#c0964a' },
  { id: 'scifi-cosmic',      label: 'Cosmic',            color: '#6050d0' },
  { id: 'scifi-retro',       label: 'Retro Sci-Fi',      color: '#c4501a' },
  { id: 'thriller',          label: 'Thriller',          color: '#cc1515' },
  { id: 'horror',            label: 'Horror',            color: '#2a6a2a' },
  { id: 'romance',           label: 'Romance',           color: '#c87060' },
]
