import asyncio
import json
import logging
from fastapi import APIRouter
from fastapi.responses import StreamingResponse
import httpx
from app.db import get_cached_dna, save_dna, get_profile, save_profile
from app.services.dna import SHELF_KEYS, extract_profile, stream_recommendations
from app.services.ol import search as ol_search
from app.timing import stage

# Validation lookups are many and small; a short timeout keeps one slow
# Open Library response from holding up a whole shelf.
VALIDATE_TIMEOUT = 3.0

logger = logging.getLogger(__name__)

router = APIRouter()

CATEGORY_LABELS = [
    "Similar Storyline",
    "Similar Tropes",
    "Similar World/Setting",
    "Same Vibe",
]


def _normalize(s: str) -> str:
    return "".join(c.lower() for c in s if c.isalnum() or c.isspace()).strip()


async def _validate_candidate(
    client: httpx.AsyncClient, candidate: dict
) -> dict | None:
    title = candidate.get("title", "")
    author = candidate.get("author", "")
    reason = candidate.get("reason", "")

    docs = await ol_search(
        {
            "title": title,
            "author": author,
            "limit": 1,
            "fields": "key,title,author_name,cover_i",
        },
        client=client,
        timeout=VALIDATE_TIMEOUT,
    )

    # docs is None (OL unreachable, no cache) or [] (not found) — skip
    if not docs:
        return None

    doc = docs[0]
    ol_norm = _normalize(doc.get("title", ""))
    cand_norm = _normalize(title)
    words = [w for w in cand_norm.split() if len(w) > 2]
    if not words:
        return None
    if sum(1 for w in words if w in ol_norm) / len(words) < 0.5:
        return None

    cover_id = doc.get("cover_i")
    return {
        "id": doc.get("key", ""),
        "title": doc.get("title", title),
        "authors": doc.get("author_name", [author]),
        "cover": (
            f"https://covers.openlibrary.org/b/id/{cover_id}-M.jpg"
            if cover_id
            else ""
        ),
        "reason": reason,
    }


async def validate_category(candidates: list, limit: int | None = 6) -> list:
    async with httpx.AsyncClient() as client:
        results = await asyncio.gather(
            *[_validate_candidate(client, c) for c in candidates]
        )
    return [r for r in results if r][:limit]


async def ensure_profile(book: dict) -> tuple[dict | None, bool]:
    """
    Return (profile, newly_created). Uses the book_profile table first,
    otherwise asks Claude and stores the result.
    """
    book_id = book.get("id", "")
    profile = get_profile(book_id) if book_id else None
    if profile is not None:
        return profile, False
    profile = await extract_profile(book)
    if profile and book_id:
        save_profile(book_id, profile)
    return profile, profile is not None


def _event(obj: dict) -> str:
    return json.dumps(obj) + "\n"


# Shelves are generated by two calls running at the same time as the profile:
# a small one for the first shelf, so it arrives fast, and one for the other
# three, which share a call so they don't repeat each other. The second call
# over-asks so de-duplication and failed validation still leave full shelves.
SHELF_SIZE = 6
SHELF_GROUPS = [
    (["Similar Storyline"], SHELF_SIZE),
    (["Similar Tropes", "Similar World/Setting", "Same Vibe"], 8),
]


async def _dna_events(book: dict):
    """
    NDJSON events for the search page, each sent as soon as it is ready:
        {"type": "profile", "profile": {...}}
        {"type": "shelf", "label": ..., "books": [...]}   per validated shelf
        {"type": "done", "fallback": bool}                always last
    The profile and both recommendation calls run concurrently; each shelf is
    validated as soon as it is generated, de-duplicated by Open Library work ID
    against the shelves already sent (and the searched book), and cut to 6.
    """
    book_id = book.get("id", "")
    shelves_sent = 0
    tasks: list[asyncio.Task] = []
    try:
        queue: asyncio.Queue = asyncio.Queue()
        counts = {"passed": 0, "suggested": 0}
        shown = {book_id}  # work IDs already on screen

        # A stored profile is sent at once and fed to the prompts; a new one is
        # extracted alongside the recommendations (which then don't wait for it).
        profile = get_profile(book_id) if book_id else None
        if profile:
            yield _event({"type": "profile", "profile": profile})
            cached = get_cached_dna(book_id)
        else:
            cached = None  # recommendations from before profiles existed are regenerated

            async def make_profile():
                with stage("profile"):
                    new, _ = await ensure_profile(book)
                if new:
                    await queue.put(("profile", new))
            tasks.append(asyncio.create_task(make_profile()))

        async def validate(label: str, candidates: list):
            with stage("validation_" + SHELF_KEYS[label]):
                valid = await validate_category(candidates, limit=None)
            counts["passed"] += len(valid)
            counts["suggested"] += len(candidates)
            await queue.put(("shelf", label, valid))

        async def generate(labels: list[str], per_shelf: int, raw: dict):
            with stage("recommendations_" + "_".join(SHELF_KEYS[l] for l in labels)):
                async for label, candidates in stream_recommendations(
                        book, profile, shelves=labels, per_shelf=per_shelf):
                    raw[label] = candidates
                    tasks.append(asyncio.create_task(validate(label, candidates)))

        async def produce():
            try:
                if cached:
                    for label in CATEGORY_LABELS:
                        tasks.append(asyncio.create_task(validate(label, cached.get(label, []))))
                else:
                    raw: dict = {}
                    await asyncio.gather(*[generate(labels, n, raw) for labels, n in SHELF_GROUPS])
                    if book_id and len(raw) == len(CATEGORY_LABELS):
                        save_dna(book_id, raw)
                # tasks grows while generation runs, so wait until it stops growing
                me = asyncio.current_task()
                while pending := [t for t in tasks if t is not me and not t.done()]:
                    await asyncio.gather(*pending)
            finally:
                await queue.put(None)

        producer = asyncio.create_task(produce())
        tasks.append(producer)
        while (item := await queue.get()) is not None:
            if item[0] == "profile":
                yield _event({"type": "profile", "profile": item[1]})
                continue
            _, label, valid = item
            books = [b for b in valid if b["id"] not in shown][:SHELF_SIZE]
            shown.update(b["id"] for b in books)
            if books:
                shelves_sent += 1
                yield _event({"type": "shelf", "label": label, "books": books})
        await producer  # re-raise anything the producer hit
        logger.info("validation passed=%d of=%d", counts["passed"], counts["suggested"])
    except Exception as e:
        logger.error("dna stream failed: %s", type(e).__name__)
    finally:
        for t in tasks:
            if not t.done():
                t.cancel()  # client went away mid-stream
    yield _event({"type": "done", "fallback": shelves_sent == 0})


@router.post("/by-category")
async def recommendations_by_category(book: dict):
    return StreamingResponse(_dna_events(book), media_type="application/x-ndjson")
